### ISSUE TITLE
Discussion: git-crypt for secrets

### ISSUE THREAD

**Issue by jchristgit** [python-discord/kubernetes#104]
Currently, our secrets are stored out-of-band, with no revision history or similar. To edit them, we need to use the cluster resources itself.
This makes it a bit cumbersome for new secrets to be introduced, or existing secrets to be updated as part of our standard git development workflow.
I propose we use [`git-crypt`](https://www.agwa.name/projects/git-crypt/), which allows us to use GPG keys (and other methods) to store encrypted files in the repository.

**Comment by Den4200** [comment]
[SOPS](https://github.com/mozilla/sops) is also a great alternative.

**Comment by spyoungtech** [comment]
To be clear, these are secrets that are only relevant to service running in our cloud infrastructure, right?

If only cloud resources really need access to the secrets, a potentially better way of doing this is using a one-way asymmetric encryption scheme. This is similar to how GitHub Actions secrets and secrets with other CI providers work, for example. Developers are provided access to an encryption key, but the private key is never exposed.

I've done this with git + AWS KMS in the past. The primary benefits of using a key management service like KMS (or equivalent with whatever cloud provider) is that the private key used for decryption is never exposed to _anybody_, and ability to decrypt can be granted and revoked via (in the case of AWS) IAM access controls. In other words, it doesn't have the problem described in AGWA/git-crypt#47

I didn't look into it too deeply, but looks like SOPS, for example, supports AWS KMS, Azure Key Vault, etc. That may be the way to go.

**Comment by jb3** [comment]
In theory we could use SOPS, store the private key in GitHub Actions and apply the manifests on change, but it's not the prettiest.

I really like the idea of using a tool like HashiCorp vault but it requires additional configuration to be able to look at environment variables.
