### ISSUE TITLE
Remove REPO_TOKEN PAT from kubernetes deploy workflows

### ISSUE THREAD

**Issue by shenanigansd** [python-discord/kubernetes#140]
This repo was previously private, and a PAT was used in workflows to access it [from other repos]. For example - https://github.com/python-discord/code-jam-management/blob/c142f98dcdeadf73ac7785facb275b35eac285b6/.github/workflows/build.yaml#L77-L84

This repo has since been made public, and this token can be removed.
The following repos will need to be updated to access this repo without the token before it can be deleted:
- [x] python-discord/bot
- [x] python-discord/site
- [x] python-discord/sir-lancebot
- [x] python-discord/sir-robin
- [x] python-discord/quackstack
- [x] python-discord/patsy
- [x] python-discord/pixels-modsite
- [x] python-discord/pixels
- [x] python-discord/king-arthur
- [x] python-discord/code-jam-management
- [x] python-discord/pixels-v2
- [x] python-discord/black-knight

This list was pulled from [CodeSearch beta access required]: https://cs.github.com/?scope=org%3Apython-discord&scopeName=python-discord&q=secrets.REPO_TOKEN
Sourcegraph link [doesn't include private repos]: https://sourcegraph.com/search?q=context:global+repo:python-discord/*+secrets.REPO_TOKEN+archived:yes+&patternType=standard

**Comment by Xithrius** [comment]
The following repositories are archived, so I deleted them from the list.
- https://github.com/python-discord/sir-threadevere
- https://github.com/python-discord/logcord

**Comment by Xithrius** [comment]
It's over, it's done.
